### ISSUE TITLE
Add main container

### ISSUE THREAD

**Issue by hmil** [CourseAdvisor/infra#2]
One way to tie everything together would be to have a main container containing the build tools (ie. npm, grunt, composer...) and having access to the infrastructure repository itself.

![schematic](http://i.imgur.com/iW5H46E.png)

**Comment by christophetd** [comment]
By "main container", do you mean "docker container"? Docker's philosophy isn't really about having one big container running multiple applications, but rather many little ones handling little parts.
E.g. a solution would be :
- a container for the DB server (which includes a database for the staging and one for the production), or maybe one for each environment
- a container for the replica of the DB server
- a container running nginx + php to serve the staging and the production
- a container running a small node script which handles github webhooks and takes care of the deployment of the application

A docker-compose.yml file may look like:

``` yaml
web: 
    image: courseadvisor/nginx-php
    volumes:
        - /var/www/courseadvisor/:/var/www/courseadvisor
    links:
        - mysql:mysql
    env_file: mysql.env # mysql credentials

mysql:
   build: mysql/ 
   # custom dockerfile and config in the mysql/ subfolder
   # for instance it may start from the mysql official image and create the courseadvisor
   #  DB structure + import the last backup

   env_file: mysql.env

mysql-slave:
   build: mysql-slave/
   # same but with mysql_slave
   link: 
     - mysql:mysql

webhook:
   image: webhook/
   # custom dockerfile installing node, devtools, and running github webhook
   env_file: github.env # github repo url, secret key...

   volumes: 
       - /var/www/courseadvisor/:var/www/courseadvisor
```

And then `docker compose up`  to run the whole thing
